-- 코드를 입력하세요
SELECT t1.ANIMAL_ID, t1.ANIMAL_TYPE, t1.NAME
FROM ANIMAL_INS AS t1
INNER JOIN ANIMAL_OUTS AS t2
ON t1.ANIMAL_ID = t2.ANIMAL_ID
WHERE t1.SEX_UPON_INTAKE != t2.SEX_UPON_OUTCOME
ORDER BY ANIMAL_ID