-- 코드를 입력하세요
SELECT t1.PRODUCT_id, T1.PRODUCT_NAME, sum(T1.PRICE * T2.AMOUNT) AS TOTLA_SALES
FROM FOOD_PRODUCT as t1
INNER JOIN FOOD_ORDER as t2
ON t1.PRODUCT_ID = t2.PRODUCT_ID
WHERE t2.PRODUCE_DATE LIKE '%2022-05-__%'
GROUP BY T1.PRODUCT_NAME
ORDER BY TOTLA_SALES DESC, PRODUCT_ID ASC;